### ISSUE TITLE
can I post your solution?

### ISSUE THREAD

**Issue by Kelvinson** [hengck23/kaggle#1]
Hi,
Dear Heng, recently I decided to start doing kaggle and found your lots of experiences and code sharing on kaggle disscussion thread. I learnt a lot from them and great thanks. Now I want to set up a repo for solution reference, can I include your solution code in it? Thanks again!

**Comment by hengck23** [comment]
Yes you can!

**Comment by Kelvinson** [comment]
Thank you Heng!
